[build]
  publish = "public"
  functions = "netlify/functions"

# /live/:slug -> 함수
[[redirects]]
  from = "/live/:slug"
  to = "/.netlify/functions/livePost/:slug"
  status = 200

# sitemap.xml -> 함수
[[redirects]]
  from = "/sitemap.xml"
  to   = "/.netlify/functions/sitemap"
  status = 200

# 나머지 전부 index.html (맨 마지막!!)
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
